steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/labseafit/mlops-reto-3', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/labseafit/mlops-reto-3']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'mlops-reto-3', '--image=gcr.io/labseafit/mlops-reto-3', '--region=us-central1', '--platform=managed']

options:
  logging: CLOUD_LOGGING_ONLY  # Para enviar logs solo a Cloud Logging


